### ISSUE TITLE
Generate planning data with one action

### ISSUE THREAD

**Issue by jkeskingvillage** [IBM/nl2flow#100]
Generate planning data with one action

Minimum Requirement:

- [x] Planning-data Generator generates planning problems with one action

**Comment by jkeskingvillage** [comment]
@TathagataChakraborti An issue from the back-end repo is moved here.

**Comment by haz** [comment]
One action problems??

**Comment by jkeskingvillage** [comment]
> One action problems??

🙈 Yeah. The title should be "Planning domains with one non-system action (i.e. an agent)"

**Comment by jkeskingvillage** [comment]
Done.
