### ISSUE TITLE
Same testing framework

### ISSUE THREAD

**Issue by TathagataChakraborti** [IBM/nl2flow#28]
+ [x] Change the unittests to pytests so we have the same thing across the board (or the other way round if we need anything specific from unittest).
+ [x] Make sure they are running as part of the rest of the tests in the CI [here](https://github.com/IBM/nl2flow/blob/main/.github/workflows/run-all-tests.yml#L35) (no change required if we are just changing to pytest).

**Comment by jkeskingvillage** [comment]
This is a legacy from a separate profiler repository.
