### ISSUE TITLE
Flags for no solution

### ISSUE THREAD

**Issue by TathagataChakraborti** [IBM/nl2flow#40]
Flag to indicate whether 

+ [x] there was no solution or the planner timed out
+ [x] there was a solution but no parse

**Comment by TathagataChakraborti** [comment]
@ctpelok77 is there a way to tell if the planner in the kstar package timed out?

**Comment by ctpelok77** [comment]
Good question. How do you use it?

**Comment by TathagataChakraborti** [comment]
like [this](https://github.com/IBM/nl2flow/blob/main/nl2flow/plan/planners.py#L79)

the whole FD output has the rest of the info outside plans doesn't it

**Comment by ctpelok77** [comment]
Yeah, I could return the raw output, but I don't think that would be very helpful. What is it you want to know? 
Was it interrupted? Was the task found unsolvable? Anything else?

**Comment by TathagataChakraborti** [comment]
Basically if there are no plans, I want to know whether it said no plans or if it was timed out. I could potentially put a time out on the call to the planner but that seems an odd thing to do given the call itself has a timeout.

**Comment by ctpelok77** [comment]
https://github.com/IBM/kstar/issues/6
