### ISSUE TITLE
Publish NL2FLOW package to PyPI

### ISSUE THREAD

**Issue by jkeskingvillage** [IBM/nl2flow#44]
Publish NL2FLOW package to PyPI.
https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Comment by TathagataChakraborti** [comment]
@jkeskingvillage check this https://pypi.org/project/nl2flow 👀

**Comment by TathagataChakraborti** [comment]
+ [x] Tested on PyPI [[link](https://pypi.org/project/nl2flow)]
+ [x] Release 0.0.2 tagged [[link](https://github.com/IBM/nl2flow/releases/tag/v0.0.2)]
+ [x] CI for push to PyPI [[link](https://github.com/IBM/nl2flow/blob/main/.github/workflows/python-publish.yml)]
