### ISSUE TITLE
Implement a basic optimization for pddl compilation at Profiler.

### ISSUE THREAD

**Issue by jkeskingvillage** [IBM/nl2flow#64]
Implement a basic optimization for pddl compilation at Profiler.

See https://github.com/IBM/nl2flow/pull/59 for detail.

```
from nl2flow.compile.options import NL2FlowOptions

flow_object.optimization_options.remove(NL2FlowOptions.multi_instance)
flow_object.optimization_options.remove(NL2FlowOptions.allow_retries)
```

Example: [example](https://github.com/IBM/nl2flow/blob/93d176a6191dfac148873e60356aed53b60c5dd3/tests/optimizations/test_no_instances.py#L34)

**Comment by TathagataChakraborti** [comment]
completed #66
