### ISSUE TITLE
Verbose prompt changes

### ISSUE THREAD

**Issue by TathagataChakraborti** [IBM/nl2flow#93]
A couple of minor changes, after going though the last results. 

+ [x] As far as I can see, none of the examples in the prompt have a slot in it? I think we should have an ask to appear in one of those 4 examples. Some of the llm responses are missing out on asks. 
+ [x] I think we should kill the variable output 😒 The outputs is adding added complexity that is making a lot of the responses add outputs in the asks and maps as well. 
  + To turn off output in the debugger and pretty print, check [this example](https://github.com/IBM/nl2flow/blob/21da151e0a3a5237669ff97d57a813003c47aaf9/tests/planner/formatting/test_codelike_print.py#L116).
  + If you are making this change, make sure to change the text in the prompt description to also not have output.
+ [x] Change _"Action a__1 has variables v__3, v__8"_ to _"Action a__1 has parameters v__3, v__8"_. I am hoping this improves the situation where the parameters are wrong in the output plan.
+ [x] The "should be known" in the action description should be "must be known" imo.

**Comment by jkeskingvillage** [comment]
The first item has nothing to do with NL2flow. ai_profiler is in a different repository, and changes are made already.

**Comment by jkeskingvillage** [comment]
@TathagataChakraborti Did you verify the impact of the proposed suggestions with at least two models?
